import type { Metadata } from "next";

import "./globals.css";
import Header from "../components/HEADER";
import Footer from "@/components/FOOTER";
import { Lobster , Playfair_Display} from 'next/font/google';



const lobster = Lobster({
  subsets:['latin'],
  weight: ['400'],
});

const playfair_display = Playfair_Display({
  subsets:['latin'],
  weight: ['400'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lobster.className} ${playfair_display.className}`}
      ><Header/>
      
        {children}
        
        <Footer/>
      </body>
    </html>
  );
}
